development:
  # adapter: async
  adapter: redis
  url: redis://redistogo:6978d64f06406d62766796c7d994b960@pearlfish.redistogo.com:10190/
  # "redis://localhost:6379/1"


test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:6978d64f06406d62766796c7d994b960@pearlfish.redistogo.com:10190/
  #  <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: phase_4_project_guidelines_production
